Minor Fixes
Calamity210/Senegal pull request #1
Opened 2020-11-08 05:59 UTC by Andy-Python-Programmer

Some Minor Fixes:

1. 
```c
for (;;) {
    
}
```

Should be written as
```c
while (true) {

}
```

2. Adding space to the `> `  indicator makes the REPL look nicer and also easy to read and debug ;)

2020-11-08 13:38 UTC, Calamity210 requested changes

2020-11-08 20:45 UTC, Andy-Python-Programmer commented on CMakeLists.txt
> +    src/core/snumCore.c
Oh

2020-11-08 21:59 UTC, Andy-Python-Programmer commented on src/main.c
> +  while (true) {
The was no difference while compiling but ;; just means infinity ♾ loop where while true one is better to read. Maybe it’s just my opinion :) So should I revert that? @Calamity210

2020-11-08 22:06 UTC, Calamity210 commented on src/main.c
> +  while (true) {
Yes please

2020-11-09 22:58 UTC, Calamity210 approved these changes

2020-11-09 22:59 UTC, Calamity210 commented
Holding on merging for now

2020-11-10 01:06 UTC, merged